org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=coalnuggets
mod.name=Coal Nuggets
mod.group=me.pajic
mod.version=1.0.7
mod.channel_tag=
mod.authors=pajic, Moonkey
mod.contributors=
mod.license=MIT
mod.description=Adds coal and charcoal nuggets
mod.sources_url=https://github.com/pajicadvance/coal-nuggets
mod.homepage_url=https://modrinth.com/mod/coal-nuggets
mod.issues_url=https://github.com/pajicadvance/coal-nuggets/issues
mod.discord_url=https://discord.gg/5RkzS66zWb

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]

publish.modrinth=iINPdcjW
publish.curseforge=1338492
publish.github=false
