# general
mod.id = "coalnuggets"
mod.name = "Coal Nuggets"
mod.group = "me.pajic"
mod.version = "1.1.0"
mod.description = "Adds coal and charcoal nuggets"
mod.authors = "pajic"
mod.contributors = ""
mod.license = "MIT"

# links
mod.sources_url = "https://github.com/pajicadvance/coal-nuggets"
mod.homepage_url = "https://modrinth.com/mod/coal-nuggets"
mod.issues_url = "https://github.com/pajicadvance/coal-nuggets/issues"
mod.discord_url = "https://discord.gg/5RkzS66zWb"

# publishing
publish.modrinth = "iINPdcjW"
publish.curseforge = "1338492"
publish.env.mr = "CLIENT_AND_SERVER" #https://modmuss50.github.io/mod-publish-plugin/platforms/modrinth/#all-options
publish.env.cf.client = true
publish.env.cf.server = true
publish.dry_run = false

# loom
loomx.loom_version = "1.17-SNAPSHOT"

# dependencies
loader.fabric = "0.19.5"
dev.runtime_optionals = []

[fabric]
dep.fabric-api.coords = "net.fabricmc.fabric-api:$id:$version"

[neoforge]


["1.21.1"]
mod.mc_releases = ["1.21", "1.21.1"]
loader.neo = "21.1.250"

[fabric."1.21.1"]
mod.mc_compat = ">=1.21 <=1.21.1"
required.fabric-api = "0.116.17+1.21.1"

[neoforge."1.21.1"]
mod.mc_compat = "[1.21, 1.21.1]"


["26.1"]
mod.mc_releases = ["26.1", "26.1.1", "26.1.2"]
loader.neo = "26.1.2.107"

[fabric."26.1"]
mod.mc_compat = "~26.1"
required.fabric-api = "0.155.3+26.1.2"

[neoforge."26.1"]
mod.mc_compat = "[26.1, 26.2)"


["26.2"]
mod.mc_releases = ["26.2"]
loader.neo = "26.2.0.82"

[fabric."26.2"]
mod.mc_compat = "~26.2"
required.fabric-api = "0.160.0+26.2"

[neoforge."26.2"]
mod.mc_compat = "[26.2, 26.3)"


["26.3"]
mod.mc_releases = ["26.3"]
#loader.neo = "26.2.0.36-beta"

[fabric."26.3"]
mod.mc_compat = "~26.3"
required.fabric-api = "0.160.5+26.3"

#[neoforge."26.2"]
#mod.mc_compat = "[26.3, 26.4)"
#required.fzzy_config = "0.7.6+26.2+neoforge"
